// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivefdcxintjpjisunnhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZWZkY3hpbnRqcGppc3Vubmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzExMTgsImV4cCI6MjA3Mjc0NzExOH0.jopJRnkUZ_14oP5Xj7jYXD9zYeei4itEBjrT8p77Vns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});